### PR TITLE
Added formatted strings for your enjoyment

### PR DESCRIPTION
**Pull request by TonyPittella**

### CODE REVIEW

**Review by TreySchneider95 — CHANGES_REQUESTED** [review]
Need to pull master and fix conflicts

**Review by TreySchneider95 — APPROVED** [review]

**Review by TreySchneider95 — CHANGES_REQUESTED** [review]
There are two -- add arguments and one has nargs '+' only need one add argument

**Review by TreySchneider95 — CHANGES_REQUESTED** [review]
The changes made here will break the multiple input feature. I would recommend pulling the master and adding "f" strings without changing the variables in the functions. Example: add_func return f"The sum of the numbers is {sum(nums)}"

**Review by TreySchneider95 — APPROVED** [review]

**Review by pchapl1 — APPROVED** [review]
niice

**Pull request merged**
